server:  port: 7777
spring:
  application:
    name: gateway-service  cloud:    gateway:      routes:      - id: users
        uri: http://localhost:8082
        predicates:        - Path=/comptes/**,/roles/**      - id: produits        uri: http://localhost:8081        predicates:        - Path=/categories/**,/produits/**                - After=2022-01-20T17:42:47.789-07:00        - Query=q        filters:        - AddResponseHeader=alpha,beta   management:  endpoints:    web:      exposure:        include: "*"